// Real local backend + React integration with synthetic files; never log in to Hope.
import fs from 'node:fs'
import path from 'node:path'
import {spawn} from 'node:child_process'
import {createRequire} from 'node:module'
import {fileURLToPath} from 'node:url'
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..')
const require=createRequire(import.meta.url)
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright')
const output=path.resolve(process.argv[2] || path.join(root,'build/product-smoke'))
fs.mkdirSync(output,{recursive:true})
const home=path.join(output,'profile'), exports=path.join(output,'exports')
const backend=spawn(process.env.HOPE_TEST_PYTHON || path.join(root,'.venv/Scripts/python.exe'),['-B','-X','utf8','-m','hope_archive.local_api'],{
  cwd:root,windowsHide:true,stdio:'ignore',env:{...process.env,HOPE_ARCHIVE_HOME:home,LOCALAPPDATA:home,PYTHONPATH:[path.join(root,'src'),path.join(root,'.venv/Lib/site-packages')].join(path.delimiter)}})
const frontend=spawn(process.execPath,[path.join(root,'frontend/vite-app/node_modules/vite/bin/vite.js')],{
  cwd:path.join(root,'frontend/vite-app'),windowsHide:true,stdio:'ignore'})
let browser, page
try {
  browser=await chromium.launch({channel:'msedge',headless:true})
  page=await browser.newPage({viewport:{width:1360,height:900}})
  const external=[];const errors=[]
  page.on('pageerror',e=>errors.push(e.message))
  await page.route('**/*',route=>{const url=new URL(route.request().url());if(!['127.0.0.1','localhost'].includes(url.hostname) && !['data:','blob:'].includes(url.protocol)){external.push(url.origin);return route.abort()}return route.continue()})
  for(let i=0;i<60;i++){try{await page.goto('http://127.0.0.1:5173');break}catch{await new Promise(r=>setTimeout(r,300))}}
  await page.getByRole('dialog',{name:'选择归档目录'}).waitFor()
  await page.getByRole('button',{name:'稍后设置'}).click()
  const labels=await page.locator('nav button').allTextContents()
  if(labels.join('|')!=='日记预览|日记归档|时间胶囊|本地搜索|识图转文字|设置')throw Error('Navigation mismatch')
  await page.getByText('请登录 Hope 后浏览云端日记。',{exact:true}).waitFor()
  await page.route('**/api/auth/login/code',route=>route.fulfill({json:{token:'fixture-session',userId:'fixture-user',displayName:'合成用户'}}))
  let cloudMode='success',previewRequest
  await page.route('**/api/diaries/preview',route=>{
    previewRequest=route.request().postDataJSON()
    if(cloudMode==='error')return route.fulfill({status:502,json:{error:'云端预览暂不可用，请检查网络连接后重试。'}})
    return route.fulfill({json:{diaries:cloudMode==='empty'?[]:[{id:'fixture',note_date:previewRequest.date,diary_type:previewRequest.diaryType,content:[{kind:'text',text:'云端合成日记，无本地归档',media:[]}],comments:[]}],hasMore:false,page:previewRequest.page}})
  })
  await page.getByRole('button',{name:'登录 Hope',exact:true}).last().click()
  await page.getByLabel('手机号',{exact:true}).fill('synthetic-test-input')
  await page.getByLabel('验证码',{exact:true}).fill('synthetic-test-code')
  await page.getByRole('button',{name:'登录',exact:true}).click()
  await page.getByText('云端合成日记，无本地归档',{exact:true}).waitFor()
  await page.getByLabel('预览日期').fill('2024-01-01')
  await page.getByLabel('日记类型').selectOption('gratitude_diary')
  await page.waitForTimeout(500)
  if(previewRequest.date!=='2024-01-01'||previewRequest.diaryType!=='gratitude_diary')throw Error('Cloud filters lost')
  cloudMode='empty';await page.getByRole('button',{name:'刷新',exact:true}).click()
  await page.getByText('当天没有此类型的云端日记。',{exact:true}).waitFor()
  cloudMode='error';await page.getByRole('button',{name:'刷新',exact:true}).click()
  await page.getByRole('alert').filter({hasText:'云端预览暂不可用'}).waitFor()
  await page.route('**/api/auth/logout',route=>route.fulfill({json:{success:true}}))
  await page.getByRole('button',{name:'退出登录',exact:true}).click()
  await page.getByText('请登录 Hope 后浏览云端日记。',{exact:true}).waitFor()
  await page.getByRole('button',{name:'本地搜索',exact:true}).click()
  if(await page.getByLabel('开始日期').inputValue() || await page.getByLabel('结束日期').inputValue())throw Error('Search dates prepopulated')
  await page.getByText('尚未归档的日记不会出现在搜索结果中。',{exact:false}).waitFor()
  await page.getByRole('textbox',{name:'关键词'}).fill('synthetic-missing')
  await page.getByRole('button',{name:'搜索',exact:true}).click()
  await page.getByText('没有找到匹配的内容，换个关键词试试吧。',{exact:true}).waitFor()
  const internalPath='hope-archive-legacy/processed/diaries.normalized.json'
  await page.route('**/api/library/search/query',route=>route.fulfill({json:{total:1,nextOffset:1,items:[{id:'fixture',date:'2024-01-01',diaryType:'gratitude_diary',contentType:'diary',snippet:'合成搜索结果',source:internalPath}]}}))
  await page.route('**/api/library/search/detail',route=>route.fulfill({json:{id:'fixture',date:'2024-01-01',diaryType:'gratitude_diary',contentType:'diary',body:'合成搜索详情',source:internalPath}}))
  await page.getByRole('button',{name:'搜索',exact:true}).click()
  await page.getByText('合成搜索结果',{exact:true}).click()
  await page.getByText('合成搜索详情',{exact:true}).waitFor()
  if((await page.locator('body').innerText()).includes(internalPath))throw Error('Internal source path visible')
  await page.getByRole('button',{name:'时间胶囊',exact:true}).click()
  if(await page.getByText('未开启',{exact:true}).count())throw Error('Unopened option visible')
  await page.getByRole('button',{name:'设置',exact:true}).click()
  await page.getByRole('heading',{name:'AI API 设置'}).waitFor()
  await page.waitForFunction(()=>document.querySelectorAll('select')[0]?.options.length===11)
  await page.getByLabel('服务商',{exact:true}).locator('option').last().waitFor({state:'attached'})
  if(await page.getByLabel('服务商',{exact:true}).locator('option').count()!==11)throw Error('Missing providers')
  await page.route('**/api/ai/status',route=>route.fulfill({json:{provider:route.request().postDataJSON().provider,configured:false,model:'custom-synthetic-model',baseUrl:'https://fixture.invalid/v1'}}))
  await page.getByLabel('服务商',{exact:true}).selectOption('anthropic')
  await page.getByLabel('模型',{exact:true}).selectOption('__custom__')
  await page.getByLabel('自定义模型 ID',{exact:true}).fill('custom-synthetic-model')
  if(await page.getByRole('button',{name:'刷新模型列表',exact:true}).isEnabled())throw Error('Discovery enabled without credentials')
  let modelRequests=0
  await page.route('**/api/ai/models',async route=>{
    modelRequests++
    const data=route.request().postDataJSON()
    if(data.apiKey!=='synthetic-test-key')throw Error('Entered key missing from explicit discovery request')
    if(modelRequests===1)await route.fulfill({json:{models:['fixture-model-a','fixture-model-b']}})
    else await route.fulfill({status:400,json:{error:'模型列表暂时不可用'}})
  })
  await page.getByLabel('API Key',{exact:true}).fill('synthetic-test-key')
  await page.getByRole('button',{name:'刷新模型列表',exact:true}).click()
  await page.getByText('发现 2 个模型，可在模型名称中选择。',{exact:true}).waitFor()
  await page.getByLabel('模型',{exact:true}).selectOption('fixture-model-b')
  await page.getByRole('button',{name:'刷新模型列表',exact:true}).click()
  await page.getByRole('alert').waitFor()
  if(await page.getByLabel('模型',{exact:true}).inputValue()!=='fixture-model-b')throw Error('Failed refresh changed model')
  await page.getByLabel('API Key',{exact:true}).fill('')
  await page.getByLabel('服务商',{exact:true}).selectOption('doubao')
  await page.getByLabel('自定义模型 ID',{exact:true}).waitFor()
  if(await page.getByRole('button',{name:'刷新模型列表',exact:true}).isEnabled())throw Error('Unsupported discovery enabled')
  if(await page.evaluate(()=>Object.keys(localStorage).some(k=>/key|credential|token/i.test(k))))throw Error('Secret persisted in browser')
  await page.screenshot({path:path.join(output,'settings.png')})
  const saved=await page.request.post('http://127.0.0.1:5173/api/settings/save',{headers:{'X-Hope-Client':'react'},data:{exportRoot:exports}})
  if(!saved.ok())throw Error('Settings persistence failed')
  await page.reload()
  await page.getByRole('button',{name:'识图转文字',exact:true}).click()
  if(await page.getByRole('dialog',{name:'选择归档目录'}).count())throw Error('Configured onboarding repeated')
  const names=['01_chinese_clear.png','02_english_clear.png','03_mixed_technical.png','16_blank.png']
  await page.locator('input[type=file]').setInputFiles(names.map(name=>path.join(root,'tests/fixtures/ocr',name)))
  if(!await page.getByRole('button',{name:'选择文件',exact:true}).isEnabled())throw Error('OCR primary picker unavailable')
  await page.getByRole('button',{name:'识别文字',exact:true}).click()
  await page.getByText('识别完成，可以逐页编辑后导出。',{exact:true}).waitFor({timeout:90000})
  await page.getByLabel('第 1 页文字').fill('编辑后的合成中文 English export')
  if(!await page.getByLabel('第 3 页文字').inputValue().then(v=>v.includes('Python')))throw Error('Mixed OCR failed')
  await page.getByText('未检测到文字，可手动输入。',{exact:true}).waitFor()
  for(const format of ['markdown','pdf','docx','tex','txt']){
    await page.getByLabel('导出格式').selectOption(format)
    await page.getByRole('button',{name:'导出编辑后的文字'}).click()
    await page.getByText(/已导出：/).waitFor()
    await page.getByRole('button',{name:'导出编辑后的文字'}).waitFor({state:'visible'})
    // Wait until the export operation releases its disabled button.
    await page.waitForFunction(()=>[...document.querySelectorAll('button')].some(b=>b.textContent==='导出编辑后的文字'&&!b.disabled))
  }
  await page.screenshot({path:path.join(output,'ocr.png')})
  const generated=fs.readdirSync(path.join(exports,'archive/ocr'))
  for(const ext of ['md','pdf','docx','tex','txt'])if(!generated.some(f=>f.endsWith('.'+ext)))throw Error('Missing export '+ext)
  const txt=generated.find(f=>f.endsWith('.txt'))
  if(!fs.readFileSync(path.join(exports,'archive/ocr',txt),'utf8').includes('编辑后的合成中文'))throw Error('Edits not exported')
  if(errors.length || external.length)throw Error('Unexpected page error or external request')
  fs.writeFileSync(path.join(output,'result.json'),JSON.stringify({navigation:labels,onboardingCancel:true,persistedExportRoot:true,blankSearchDates:true,openedOnly:true,providers:11,realOCR:true,editableResult:true,formats:5,externalRequests:external,javascriptErrors:errors},null,2))
  console.log('PASS: real product UI, onboarding, settings, six navigation sections, offline OCR and five edited exports')
}catch(error){if(page){await page.screenshot({path:path.join(output,'failure.png')}).catch(()=>{});console.log('Synthetic test alerts:',await page.getByRole('alert').allTextContents())}throw error}finally{if(browser)await browser.close();backend.kill();frontend.kill()}
